#!/usr/bin/env python3
"""Email generated EPUB digests to a Kindle address and record delivery state."""

from __future__ import annotations

import argparse
import json
import os
import smtplib
import ssl
import sys
from datetime import datetime, timezone
from email.message import EmailMessage
from pathlib import Path
from typing import Any


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--manifest", default="dist/manifest.json")
    parser.add_argument("--state", default="state/kindle.json")
    parser.add_argument("--smtp-host", default="smtp.gmail.com")
    parser.add_argument("--smtp-port", type=int, default=465)
    return parser.parse_args()


def required_env(name: str) -> str:
    value = os.environ.get(name, "").strip()
    if not value:
        raise RuntimeError(f"Required environment variable {name} is not set.")
    return value


def load_json(path: Path, default: dict[str, Any]) -> dict[str, Any]:
    if not path.exists():
        return default
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError) as exc:
        raise RuntimeError(f"Could not read {path}: {exc}") from exc


def save_state(path: Path, state: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    state["updated_at"] = datetime.now(timezone.utc).isoformat()
    path.write_text(json.dumps(state, indent=2) + "\n", encoding="utf-8")


def send_epub(
    smtp: smtplib.SMTP_SSL,
    username: str,
    kindle_email: str,
    section: str,
    epub_path: Path,
) -> None:
    message = EmailMessage()
    message["From"] = username
    message["To"] = kindle_email
    message["Subject"] = epub_path.stem
    message.set_content(f"{section} RSS digest generated by rss-to-kindle.")
    message.add_attachment(
        epub_path.read_bytes(),
        maintype="application",
        subtype="epub+zip",
        filename=epub_path.name,
    )
    smtp.send_message(message)


def main() -> int:
    args = parse_args()
    manifest_path = Path(args.manifest)
    state_path = Path(args.state)

    manifest = load_json(manifest_path, {"sections": []})
    sections = manifest.get("sections", [])
    if not sections:
        print("No EPUBs to deliver.")
        return 0

    username = required_env("SMTP_USERNAME")
    password = required_env("SMTP_APP_PASSWORD")
    kindle_email = required_env("KINDLE_EMAIL")

    state = load_json(state_path, {"sent_article_ids": [], "deliveries": []})
    sent_ids = set(state.get("sent_article_ids", []))
    deliveries = list(state.get("deliveries", []))
    failures: list[str] = []

    context = ssl.create_default_context()
    with smtplib.SMTP_SSL(
        args.smtp_host,
        args.smtp_port,
        context=context,
        timeout=30,
    ) as smtp:
        smtp.login(username, password)

        for item in sections:
            section = str(item["section"])
            epub_path = Path(item["path"])
            article_ids = [str(value) for value in item.get("article_ids", [])]

            if not epub_path.exists():
                failures.append(f"{section}: missing {epub_path}")
                continue

            try:
                send_epub(smtp, username, kindle_email, section, epub_path)
            except Exception as exc:
                failures.append(f"{section}: {exc}")
                print(f"Delivery failed for {section}: {exc}", file=sys.stderr)
                continue

            sent_ids.update(article_ids)
            deliveries.append(
                {
                    "section": section,
                    "delivered_at": datetime.now(timezone.utc).isoformat(),
                    "article_count": len(article_ids),
                    "filename": epub_path.name,
                }
            )
            # Save after each accepted email. If a later section fails, this
            # section will not be sent again on the next run.
            state["sent_article_ids"] = sorted(sent_ids)
            state["deliveries"] = deliveries[-100:]
            save_state(state_path, state)
            print(f"Delivered {epub_path.name} to Kindle ({len(article_ids)} articles).")

    if failures:
        print("One or more deliveries failed:", file=sys.stderr)
        for failure in failures:
            print(f"- {failure}", file=sys.stderr)
        return 1

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
